### ISSUE TITLE
请问一下，centos6.7下面安装完成后，启动时报错

### ISSUE THREAD

**Issue by coco1960** [itead/IoTgo#12]
[root@localhost IoTgo]# DEBUG="iotgo" ./bin/www

/root/IoTgo/config.js:25
  mailgun: {
  ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/IoTgo/routes/http.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/IoTgo/routes/index.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

这是什么原因？
配置文件
[root@localhost IoTgo]# cat config.js
module.exports = {
  host: 'localhost',        // Hostname of IoTgo platform
  db: {  
    uri: 'mongodb://localhost/iotgo',   // MongoDB database address
    options: {
      user: 'iotgo',                    // MongoDB database username
      pass: 'iotgo'                     // MongoDB database password
    }
  },
  jwt: {
    secret: 'jwt_secret'                // Shared secret to encrypt JSON Web Token
  },
  admin:{
    'iotgo@iteadstudio.com': 'password' // Administrator account of IoTgo platform
  },
  page: {
    limit: 50,                          // Default query page limit
    sort: -1                            // Default query sort order
  },
  recaptcha: {
      secret: '',                       // Google reCAPTCHA serect
      url: 'https://www.google.com/recaptcha/api/siteverify'
    },
  pendingRequestTimeout: 3000
  mailgun: {
          api_key:'',                   //Mailgun API Key
          domain:'',                    //Mailgun Domain Name
          from:''                       //Mailgun Default SMTP Login Email
  },
  upgradeUrl:"http://v.itead.cc/api/upgrade"
};
另外一定要用google的验证码系统吗？

**Comment by humingchun** [comment]
config.js 是一个 JavaScript 文件，你给出的 config.js 里 pengdingRequestTimeout: 3000 后面少了一个英文逗号，就不是合法的 JS 文件了。

mailgun 是一个邮件发送服务，你也可以换其他家的。

Google reCaptcha 分为前后台部分，你不用的话，在前台注册页面注销相应 JS 代码，在后台认证接口部分注销相应代码就可以了。

**Comment by coco1960** [comment]
感谢回答，config.js是cp例子的，只改了hostname.
mongodb 不是自动配置的吗？

**Comment by humingchun** [comment]
恩，config.js 在上一次 commit 的时候漏掉了那个逗号。

MongoDB 需要指定 DB 的名称、用户名跟密码的，不是自动配置的。这个跟传统的 LAMP 架构是一样的，需要先配置 MySQL 数据库，然后在 PHP 里配置数据库的信息。

**Comment by sunfeng90** [comment]
你好，你这个项目不维护了吗？我可以帮你维护吗？

**Comment by sunfeng90** [comment]
我会写上原文地址的，可以吗？

**Comment by mohamedmostafaa** [comment]
i have another problem in the same issue please help????????

**Comment by mohamedmostafaa** [comment]
pi@raspberrypi:~ $ DEBUG="iotgo" /home/pi/IoTgo/bin/www
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/home/pi/IoTgo/config.js:32
});
 ^

**Comment by sunfeng90** [comment]
版本不同，所以会报错

**Comment by mohamedmostafaa** [comment]
i don't understand what do you mean?

**Comment by mohamedmostafaa** [comment]
how i configure the mongodb to work with the server Please help me???

**Comment by sunfeng90** [comment]
@mohamedmostafaa Where are you from?

**Comment by sunfeng90** [comment]
@mohamedmostafaa You only  run the project in the version of 6.*

**Comment by mohamedmostafaa** [comment]
i get this erorr
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/users?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/users?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/users?limit=50 - - ms - -
POST /api/admin/factorydevices/create - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
any ideas

**Comment by mohamedmostafaa** [comment]
@sunfeng90  I'm from egypt

**Comment by mohamedmostafaa** [comment]
@sunfeng90  i solve all previous issue but still to response from server to create batch
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/users?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/users?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
GET /api/admin/users?limit=50 - - ms - -
POST /api/admin/factorydevices/create - - ms - -
GET /api/admin/factorydevices?limit=50 - - ms - -
GET /api/admin/devices?limit=50 - - ms - -
any ideas

**Comment by mohamedmostafaa** [comment]
![server error_1](https://user-images.githubusercontent.com/19883681/40868719-62d773d0-6618-11e8-978e-aa92165cd1a4.png)
![server error_2](https://user-images.githubusercontent.com/19883681/40868725-6f171600-6618-11e8-9b92-c71081baab68.png)
![server error_3](https://user-images.githubusercontent.com/19883681/40868726-7806393a-6618-11e8-903f-14ed5753bfe3.png)
@sunfeng90  this the error msg
can you help me???????

**Comment by sunfeng90** [comment]
@mohamedmostafaa what's the NodeJs version do you use?

**Comment by sunfeng90** [comment]
@mohamedmostafaa I have delete any codes of this project.The new version's address is https://github.com/sunfeng90/IoTgo-Pro, you can clone it.If you have any problem, contact  with me.

**Comment by mohamedmostafaa** [comment]
@sunfeng90  many thanks for your support i'm gonna to clone your file and try again

**Comment by mohamedmostafaa** [comment]
![iotgopro](https://user-images.githubusercontent.com/19883681/40891551-20cfb8de-6790-11e8-9d5b-afd285f193fe.png)
@sunfeng90  when i clone your file this error occurred
any idea?

**Comment by mohamedmostafaa** [comment]
@sunfeng90 00201222289909 my whats' app no

**Comment by sunfeng90** [comment]
@mohamedmostafaa  00201222289909 my whats' app no, What's your mean?

**Comment by sunfeng90** [comment]
@mohamedmostafaa I will give you answers this night.

**Comment by mohamedmostafaa** [comment]
@sunfeng90 many thanks for you 
i hope that you help me till i finish this project

**Comment by mohamedmostafaa** [comment]
@sunfeng90  i mean if you want to communicate faster on what;s app i have no problem

**Comment by sunfeng90** [comment]
@mohamedmostafaa Do you use any other communicate apps? For example weChat. I'm from China.

**Comment by sunfeng90** [comment]
@mohamedmostafaa I have study this project and deleted any unused codes.I will give you my codes this night.

**Comment by sunfeng90** [comment]
@mohamedmostafaa I haven't use the what;s app. I use QQ、WeChat and Email more.

**Comment by mohamedmostafaa** [comment]
@sunfeng90  yes i use wechat

**Comment by mohamedmostafaa** [comment]
MY ID : wxid_14cbpjnw2j4422

**Comment by mohamedmostafaa** [comment]
@sunfeng90 MY ID : wxid_14cbpjnw2j4422

**Comment by sunfeng90** [comment]
@mohamedmostafaa I cann't find you in wechat.I suggest you update it to a short one.My id is: fwzkj90

**Comment by mohamedmostafaa** [comment]
iotgo Connect to DB failed! +291ms
any help
