### ISSUE TITLE
cann't login in

### ISSUE THREAD

**Issue by widora** [itead/IoTgo#16]
error: Email address or password is not correct!
my config.js is:
 admin:{
    'widora@qq.com': '12345678' // Administrator account of IoTgo platform
  },

but cann't login.

the log:
root@iZ285zrpk4eZ:~/IoTgo# DEBUG="iotgo" PORT=3000 ./bin/www
  iotgo Express server listening on port 3000 +0ms
  iotgo Connect to DB successful! +180ms
GET /login 302 12.267 ms - 70
POST /api/user/login 200 28.361 ms - 53

**Comment by mohamedmostafaa** [comment]
iotgo Connect to DB failed! +291ms
any help

**Comment by mohamedmostafaa** [comment]
iotgo MongoError: auth fails
    at Object.toError (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/pi/IoTgo/node_modules/mongodb/lib/mongodb/db.js:1196:31
    at /home/pi/IoTgo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at .<anonymous> (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18) +6ms

**Comment by mohamedmostafaa** [comment]
iotgo Error: failed to connect to [localhost:27017]
