### ISSUE TITLE
我可以帮助你维护这个项目吗？

### ISSUE THREAD

**Issue by sunfeng90** [itead/IoTgo#17]
你好，发现这个项目已经有两年没有更新了。我比较喜欢你这个项目，我可以帮助你维护吗？

**Comment by sunfeng90** [comment]
我准备在  https://github.com/sunfeng90/IoTgo-Pro  帮你维护，里面添加你的信息了。

**Comment by mohamedmostafaa** [comment]
i can't connect to the data base? any help?

**Comment by sunfeng90** [comment]
@mohamedmostafaa No problem.

**Comment by mohamedmostafaa** [comment]
iotgo Connect to DB failed! +291ms
any help???

**Comment by mohamedmostafaa** [comment]
iotgo MongoError: auth fails
    at Object.toError (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/pi/IoTgo/node_modules/mongodb/lib/mongodb/db.js:1196:31
    at /home/pi/IoTgo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at .<anonymous> (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/pi/IoTgo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18) +6ms
