### ISSUE TITLE
Erro while trying to start application on windows system

### ISSUE THREAD

**Issue by vatsalmevada** [itead/IoTgo#2]
I am trying to execute application on windows by using following command:

```
node www
```

However I ma facing following error: 

```
C:\Users\lenovo\Documents\shared with VM\iotgo\IoTgo\node_modules\bcrypt\node_modules\bindings\bindings.js:79
        throw e
              ^
Error: %1 is not a valid Win32 application.
C:\Users\lenovo\Documents\shared with VM\iotgo\IoTgo\node_modules\bcrypt\build\Release\bcrypt_lib.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (C:\Users\lenovo\Documents\shared with VM\iotgo\IoTgo\node_modules\bcrypt\node_modules\bindings\bindings
.js:74:15)
    at Object.<anonymous> (C:\Users\lenovo\Documents\shared with VM\iotgo\IoTgo\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I am newbie to MEAN stack. So pardon me if the resolution is too obvious.

**Comment by hellojavajs** [comment]
Sorry, we do not support windows system environment, as an open source cloud platform services, Linux  supports  more 3rd party software, no system is more suitable than Linux

**Comment by vatsalmevada** [comment]
I have hosted on Linux only. Still I wanted to debug the application using IDE. And I am was having IDE for Linux. Anyways thanks.
